services:
  - type: web
    name: Health-Metrics
    env: python
    buildCommand: ""
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: DATABASE_URL
        value: "sqlite:///data/health_metrics.sqlite"